// Single-file copy of supabase/functions/planner-push (index.ts + core.js) for pasting into the
// Supabase dashboard editor. Generated by `npm run bundle`; edit the originals, not this file.
// Uni Planner notification sender.
// Called every minute by pg_cron (header x-cron-secret), and by the app's "Send test" button (user's login token).
// Settings: VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT, CRON_SECRET — read from Edge Function secrets,
// or else from the server-only table public.planner_private. SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are automatic.
import { createClient } from 'npm:@supabase/supabase-js@2';

// ===== core.js =====
// Shared by the app (preview of upcoming notifications) and the Supabase function (sending them).
// Plain JavaScript with no imports, so it runs in the browser, in Deno and in Node tests.

// ---------------------------------------------------------------------------
// Time helpers. Kuwait has no daylight saving, so a fixed offset (UTC+3 = 180 min) is exact.
// ---------------------------------------------------------------------------
const DAY = 86400000;
export const pad = n => String(n).padStart(2, '0');

// Local wall-clock date + "HH:MM" -> UTC milliseconds.
export function localToMs(dateStr, timeStr, offsetMin) {
  const [y, m, d] = dateStr.split('-').map(Number);
  const [h, mi] = String(timeStr || '00:00').split(':').map(Number);
  return Date.UTC(y, m - 1, d, h, mi) - offsetMin * 60000;
}
// UTC milliseconds -> { date: 'YYYY-MM-DD', time: 'HH:MM', dow: 0..6 } in local time.
export function msToLocal(ms, offsetMin) {
  const t = new Date(ms + offsetMin * 60000);
  return {
    date: `${t.getUTCFullYear()}-${pad(t.getUTCMonth() + 1)}-${pad(t.getUTCDate())}`,
    time: `${pad(t.getUTCHours())}:${pad(t.getUTCMinutes())}`,
    dow: t.getUTCDay()
  };
}
export function addDays(dateStr, n) {
  const [y, m, d] = dateStr.split('-').map(Number);
  const t = new Date(Date.UTC(y, m - 1, d) + n * DAY);
  return `${t.getUTCFullYear()}-${pad(t.getUTCMonth() + 1)}-${pad(t.getUTCDate())}`;
}
const hhmm = t => String(t || '').slice(0, 5);
const DOW = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
export function prettyDate(dateStr) {
  const [y, m, d] = dateStr.split('-').map(Number);
  return `${DOW[new Date(Date.UTC(y, m - 1, d)).getUTCDay()]} ${d} ${MON[m - 1]}`;
}

export const COURSE_NAMES = {
  'BIOL 110': 'Biology', 'MA 265': 'Linear Algebra', 'CE 337': 'ASIC Design Lab',
  'CE 462': 'OOP C++/Java', 'CE 468': 'Compilers', 'CE 400': 'Grad Project I'
};
export const KIND_LABELS = {
  gca: 'GCA', exam: 'Exam', quiz: 'Quiz', assignment: 'Assignment', hw: 'Homework',
  lab: 'Graded lab', prelab: 'Pre-lab', project: 'Project', info: 'Info', academic: 'Academic'
};
export const DEFAULT_SETTINGS = {
  tz_offset_min: 180,
  class_leads: [60, 30],
  day_before_time: '20:00',
  term_start: '2026-09-20',
  term_end: '2027-01-14',
  skip_dates: [],
  notify_classes: true,
  notify_events: true,
  event_kinds: ['gca', 'exam', 'quiz', 'assignment', 'hw', 'lab', 'prelab', 'project']
};
const withDefaults = s => ({ ...DEFAULT_SETTINGS, ...(s || {}) });

// ---------------------------------------------------------------------------
// Reminder schedule. Each reminder has a stable key so it is sent only once.
// ---------------------------------------------------------------------------
const leadText = m => m % 60 === 0 ? (m === 60 ? '1 hour' : `${m / 60} hours`) : `${m} minutes`;

// Class reminders whose send time falls in (fromMs, toMs].
export function classReminders(settingsIn, classes, fromMs, toMs) {
  const s = withDefaults(settingsIn);
  if (!s.notify_classes) return [];
  const off = s.tz_offset_min, skip = new Set(s.skip_dates || []);
  const leads = (s.class_leads || []).map(Number).filter(n => n > 0);
  const maxLead = Math.max(0, ...leads);
  const out = [];
  let date = msToLocal(fromMs, off).date;
  const lastDate = msToLocal(toMs + maxLead * 60000, off).date;
  for (; date <= lastDate; date = addDays(date, 1)) {
    if (date < s.term_start || date > s.term_end || skip.has(date)) continue;
    const dow = msToLocal(localToMs(date, '12:00', off), off).dow;
    for (const c of classes) {
      if (Number(c.weekday) !== dow) continue;
      const start = localToMs(date, hhmm(c.start_time), off);
      for (const lead of leads) {
        const at = start - lead * 60000;
        if (at <= fromMs || at > toMs) continue;
        out.push({
          key: `c:${c.id}:${date}:${lead}`, at, kind: 'class',
          title: `${c.course} ${c.kind === 'Lab' ? 'lab' : 'class'} in ${leadText(lead)}`,
          body: `${hhmm(c.start_time)}–${hhmm(c.end_time)}${c.room ? ' · ' + c.room : ''}`,
          tag: `class-${c.id}-${date}`
        });
      }
    }
  }
  return out;
}

// Day-before reminders for graded work, sent at day_before_time on the previous day.
export function eventReminders(settingsIn, events, fromMs, toMs) {
  const s = withDefaults(settingsIn);
  if (!s.notify_events) return [];
  const off = s.tz_offset_min, kinds = new Set(s.event_kinds || []);
  const out = [];
  for (const e of events) {
    if (e.done || e.remind === false || !kinds.has(e.kind)) continue;
    const dueMs = new Date(e.due_at).getTime();
    const due = msToLocal(dueMs, off);
    const at = localToMs(addDays(due.date, -1), s.day_before_time, off);
    if (at <= fromMs || at > toMs) continue;
    const label = e.kind === 'assignment' || e.kind === 'hw' || e.kind === 'prelab' ? 'due' : 'tomorrow';
    out.push({
      key: `e:${e.id}:${dueMs}`, at, kind: 'event',
      title: `Tomorrow: ${e.course} ${e.title}`,
      body: `${prettyDate(due.date)}${e.all_day ? '' : (label === 'due' ? ', due ' : ', ') + due.time}${e.weight ? ' · ' + e.weight : ''}${e.note ? ' · ' + e.note : ''}`,
      tag: `event-${e.id}`
    });
  }
  return out;
}

export function remindersBetween(settings, classes, events, fromMs, toMs) {
  return [...classReminders(settings, classes, fromMs, toMs), ...eventReminders(settings, events, fromMs, toMs)]
    .sort((a, b) => a.at - b.at);
}

// ---------------------------------------------------------------------------
// Web Push (RFC 8291 aes128gcm payload encryption + RFC 8292 VAPID), WebCrypto only.
// ---------------------------------------------------------------------------
const enc = new TextEncoder();
export function b64urlToBytes(s) {
  s = s.replace(/-/g, '+').replace(/_/g, '/');
  while (s.length % 4) s += '=';
  const bin = atob(s); const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
export function bytesToB64url(bytes) {
  let bin = ''; const b = new Uint8Array(bytes);
  for (let i = 0; i < b.length; i++) bin += String.fromCharCode(b[i]);
  return btoa(bin).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
const concat = (...parts) => {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0)); let o = 0;
  for (const p of parts) { out.set(p, o); o += p.length; } return out;
};
async function hkdf(salt, ikm, info, bytes) {
  const key = await crypto.subtle.importKey('raw', ikm, 'HKDF', false, ['deriveBits']);
  return new Uint8Array(await crypto.subtle.deriveBits({ name: 'HKDF', hash: 'SHA-256', salt, info }, key, bytes * 8));
}

// Encrypts a payload for one subscription. Returns the request body bytes.
export async function encryptPayload(plaintext, p256dhB64, authB64, opts = {}) {
  const uaPublic = b64urlToBytes(p256dhB64), authSecret = b64urlToBytes(authB64);
  const asKeys = opts.asKeys || await crypto.subtle.generateKey({ name: 'ECDH', namedCurve: 'P-256' }, true, ['deriveBits']);
  const asPublic = new Uint8Array(await crypto.subtle.exportKey('raw', asKeys.publicKey));
  const uaKey = await crypto.subtle.importKey('raw', uaPublic, { name: 'ECDH', namedCurve: 'P-256' }, false, []);
  const ecdh = new Uint8Array(await crypto.subtle.deriveBits({ name: 'ECDH', public: uaKey }, asKeys.privateKey, 256));
  const ikm = await hkdf(authSecret, ecdh, concat(enc.encode('WebPush: info\0'), uaPublic, asPublic), 32);
  const salt = opts.salt || crypto.getRandomValues(new Uint8Array(16));
  const cek = await hkdf(salt, ikm, enc.encode('Content-Encoding: aes128gcm\0'), 16);
  const nonce = await hkdf(salt, ikm, enc.encode('Content-Encoding: nonce\0'), 12);
  const aes = await crypto.subtle.importKey('raw', cek, 'AES-GCM', false, ['encrypt']);
  const padded = concat(typeof plaintext === 'string' ? enc.encode(plaintext) : plaintext, new Uint8Array([2]));
  const cipher = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-GCM', iv: nonce }, aes, padded));
  const header = new Uint8Array(21 + asPublic.length);
  header.set(salt, 0);
  new DataView(header.buffer).setUint32(16, 4096);
  header[20] = asPublic.length;
  header.set(asPublic, 21);
  return concat(header, cipher);
}

// Signed VAPID header for an endpoint's push service.
export async function vapidAuthorization(endpoint, vapidPublicB64, vapidPrivateB64, subject) {
  const pub = b64urlToBytes(vapidPublicB64);
  const jwk = { kty: 'EC', crv: 'P-256', d: vapidPrivateB64, x: bytesToB64url(pub.slice(1, 33)), y: bytesToB64url(pub.slice(33, 65)), ext: true };
  const key = await crypto.subtle.importKey('jwk', jwk, { name: 'ECDSA', namedCurve: 'P-256' }, false, ['sign']);
  const head = bytesToB64url(enc.encode(JSON.stringify({ typ: 'JWT', alg: 'ES256' })));
  const body = bytesToB64url(enc.encode(JSON.stringify({ aud: new URL(endpoint).origin, exp: Math.floor(Date.now() / 1000) + 12 * 3600, sub: subject })));
  const sig = await crypto.subtle.sign({ name: 'ECDSA', hash: 'SHA-256' }, key, enc.encode(`${head}.${body}`));
  return `vapid t=${head}.${body}.${bytesToB64url(sig)}, k=${vapidPublicB64}`;
}

// Sends one notification. Returns the push service's HTTP status (201 = accepted; 404/410 = subscription gone).
export async function sendPush(sub, payload, vapid, ttlSeconds = 3600) {
  const body = await encryptPayload(JSON.stringify(payload), sub.p256dh, sub.auth);
  const res = await fetch(sub.endpoint, {
    method: 'POST',
    headers: {
      Authorization: await vapidAuthorization(sub.endpoint, vapid.publicKey, vapid.privateKey, vapid.subject),
      'Content-Encoding': 'aes128gcm',
      'Content-Type': 'application/octet-stream',
      TTL: String(ttlSeconds),
      Urgency: 'high'
    },
    body
  });
  return res.status;
}

// ===== index.ts =====

const env = (k: string) => Deno.env.get(k) ?? '';
const db = createClient(env('SUPABASE_URL'), env('SUPABASE_SERVICE_ROLE_KEY'), { auth: { persistSession: false } });
const vapid = { publicKey: '', privateKey: '', subject: '' };
let cronSecret = '';
let configLoaded = false;
async function loadConfig() {
  if (configLoaded) return;
  const { data } = await db.from('planner_private').select('key,value');
  const t = Object.fromEntries((data ?? []).map(r => [r.key, r.value]));
  const get = (k: string) => env(k) || t[k] || '';
  vapid.publicKey = get('VAPID_PUBLIC_KEY'); vapid.privateKey = get('VAPID_PRIVATE_KEY');
  vapid.subject = get('VAPID_SUBJECT') || 'mailto:planner@example.com';
  cronSecret = get('CRON_SECRET');
  if (!vapid.publicKey || !vapid.privateKey || !cronSecret) throw new Error('Notification keys are not set up.');
  configLoaded = true;
}
const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, apikey, content-type, x-client-info',
  'Access-Control-Allow-Methods': 'POST, OPTIONS'
};
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...CORS, 'Content-Type': 'application/json' } });

// A run looks back 15 minutes, so a late or skipped cron run still delivers; the sent log stops repeats.
const LOOKBACK_MS = 15 * 60000;

async function deliver(userId: string, subs: any[], payload: Record<string, unknown>) {
  let ok = 0;
  for (const s of subs.filter(x => x.user_id === userId)) {
    try {
      const status = await sendPush(s, payload, vapid);
      if (status === 404 || status === 410) await db.from('planner_push_subs').delete().eq('endpoint', s.endpoint);
      else if (status >= 200 && status < 300) ok++;
      else console.error('push failed', status, s.endpoint.slice(0, 60));
    } catch (e) { console.error('push error', e); }
  }
  return ok;
}

async function runSchedule() {
  const now = Date.now(), from = now - LOOKBACK_MS;
  const { data: subs, error: e1 } = await db.from('planner_push_subs').select('*');
  if (e1) throw e1;
  const users = [...new Set((subs ?? []).map(s => s.user_id))];
  if (!users.length) return { users: 0, sent: 0 };
  const [{ data: settings }, { data: classes }, { data: events }] = await Promise.all([
    db.from('planner_settings').select('*').in('user_id', users),
    db.from('planner_classes').select('*').in('user_id', users),
    db.from('planner_events').select('*').in('user_id', users).eq('done', false)
      .gte('due_at', new Date(now - 2 * 86400000).toISOString()).lte('due_at', new Date(now + 3 * 86400000).toISOString())
  ]);
  let sent = 0;
  for (const uid of users) {
    const s = (settings ?? []).find(x => x.user_id === uid);
    if (!s) continue;
    const due = remindersBetween(s, (classes ?? []).filter(c => c.user_id === uid), (events ?? []).filter(e => e.user_id === uid), from, now);
    for (const r of due) {
      // Claim the reminder first; if the row already exists it was sent before, so skip it.
      const { data: claimed, error } = await db.from('planner_sent')
        .upsert({ user_id: uid, key: r.key }, { onConflict: 'user_id,key', ignoreDuplicates: true }).select('key');
      if (error) { console.error(error); continue; }
      if (!claimed?.length) continue;
      sent += await deliver(uid, subs!, { title: r.title, body: r.body, tag: r.tag, url: './' });
    }
  }
  if (new Date(now).getUTCMinutes() === 0) await db.rpc('planner_prune_sent');
  return { users: users.length, sent };
}

Deno.serve(async req => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: CORS });
  try {
    await loadConfig();
    const secret = req.headers.get('x-cron-secret');
    if (secret && secret === cronSecret) return json(await runSchedule());

    // Otherwise it must be the signed-in app asking for a test notification.
    const token = (req.headers.get('authorization') ?? '').replace(/^Bearer\s+/i, '');
    const { data: { user } } = token ? await db.auth.getUser(token) : { data: { user: null } };
    if (!user) return json({ error: 'Sign in again, then retry.' }, 401);
    const { data: subs } = await db.from('planner_push_subs').select('*').eq('user_id', user.id);
    if (!subs?.length) return json({ error: 'This account has no devices with notifications turned on.' }, 400);
    const ok = await deliver(user.id, subs, { title: 'Uni Planner', body: 'Notifications are working on this device.', tag: 'test', url: './' });
    return json({ devices: subs.length, delivered: ok });
  } catch (e) {
    console.error(e);
    return json({ error: String((e as Error)?.message ?? e) }, 500);
  }
});
